### ISSUE TITLE
README.md correction for Examples

### ISSUE THREAD

**Issue by holisticinfosec** [sans-blue-team/DeepBlueCLI#16]
Greetings SANS Blue Team,

Under **Examples**, current example commands for Metasploit PowerShell target (security) and Metasploit PowerShell target (system) are a repeat of the previous native commands.

Metasploit PowerShell target (security) should be ```.\DeepBlue.ps1 .\evtx\metasploit-psexec-powershell-target-security.evtx``` and Metasploit PowerShell target (system) should be
```.\DeepBlue.ps1 .\evtx\metasploit-psexec-powershell-target-system.evtx```

I can fork, fix, and send you a pull request if you prefer.
Cheers, Russ

**Comment by eric-conrad** [comment]
Thank you!

Fixed.
