### ISSUE TITLE
Errors on Application.evtx

### ISSUE THREAD

**Issue by RandyRandleman** [sans-blue-team/DeepBlueCLI#17]
Getting the following error on Application.evtx with known logs within it. 

Get-WinEvent @{path="C\Windows\System32\winevt\logs\Application.evtx";ID=2} -ErrorAction Stop
Get-WinEvent error:  No events were found that match the specified selection criteria.

**Comment by joswr1ght** [comment]
Is your PowerShell session opened as an Administrator? Are there any logs in that evtx file? Thanks!

**Comment by RandyRandleman** [comment]
Disregard, Josh. I see now which Events are being pulled!

**Comment by joswr1ght** [comment]
Awesome! Glad it’s working for you. Thanks for reaching out. 👊
